#!/usr/bin/env node
/**
 * Generate PDF for Resume Interview Assistant
 * Contains the resume optimization suggestions from the latest dialog
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');

// Output file
const outputFile = '/home/agent/.claude/workspace/project/uploads/resume_optimization_guide.pdf';

// Content from the latest dialog
const content = `Resume Optimization Guide
Software Engineer (AI) Position

Based on the resume analysis for: 姜植藂

===========================================

CURRENT RESUME SUMMARY
===========================================

Personal Info:
- Name: 姜植藂
- Location: 北京通州
- Email: jiangzhicong2516@163.com
- Phone: 17600192516

Education:
- 中国政法大学 - 国际贸易学硕士 (2015-2018)
- 中国地质大学 - 数学与应用数学学士 (2009-2013)

Work Experience:
1. 北京外企德科人力资源有限公司 - 安全运营工程师/软件开发工程师 (2023.2-2025.4)
2. 北京盛创恒达房地产开发有限公司 - 算法工程师 (2018.7-2023.1)

Skills: Python、Java | 云计算安全、推荐算法、数据分析

===========================================

JOB REQUIREMENTS ANALYSIS
===========================================

Software Engineer (AI) Core Requirements:
1. Design and deliver AI-driven Web/Mobile products
2. Full-stack development + AI/ML deep interest
3. Build scalable, user-focused applications
4. Cross-functional collaboration + end-to-end development
5. AI model integration optimization + mentoring

===========================================

RESUME MODIFICATION SUGGESTIONS
===========================================

1. STRENGTHEN AI/ML RELATED EXPERIENCE
--------------------------------------
Current:
"召回率从 2% 提升至 5%，排序模型 AUC 达到 75%"

Recommended:
主导推荐系统算法优化，采用 Word2vec 进行物品 embedding 计算，结合用户行为序列进行兴趣建模，AUC 提升至 75%，召回率提升 150%（2%→5%）

Reason: Use technical terms to accurately describe AI algorithm work, reflecting data-driven thinking.

2. HIGHLIGHT FULL-STACK DEVELOPMENT SKILLS
------------------------------------------
Current Project: 安全运营看板

Recommended Additions:
- Frontend tech stack (if any)
- Database design (SQL)
- Log collection system architecture (ELK/Log Platform)

Recommended Description:
主导安全运营看板端到端开发，从架构设计到技术选型（Python + SQL + 可视化库），实现日志收集、存储、清洗、分析全链路，日处理数据量达百万级

3. ADD AI PRODUCT RELATED DESCRIPTIONS
---------------------------------------
In project descriptions, include:
- AI model training/deployment involved
- User experience optimization
- Product iteration

Recommended New Project Highlights:
推荐系统日均服务用户请求 XX 次，算法响应时间 < 100ms，支撑业务 GMV 增长 XX%

4. STRENGTHEN CROSS-TEAM COLLABORATION
--------------------------------------
Recommended additions to project management:
- Coordinate with security team, development team, product team
- Close collaboration with data analysts
- Guide junior engineers

5. SKILLS MODULE RESTRUCTURE
----------------------------
Current:                       Recommended:
编程语言：Python、Java     →  编程语言：Python、Java、SQL、Shell
擅长领域：云计算安全...   →  擅长领域：
                              • AI/ML：推荐算法、NLP基础、模型优化
                              • 全栈开发：Web/Mobile 后端架构
                              • 数据工程：ETL、大数据分析、可视化
                              • 云安全：身份认证、权限管理

===========================================

RECOMMENDED RESUME STRUCTURE
===========================================

【Recommended Title】
Software Engineer | AI/ML | Full-Stack Developer

1. Technical Summary (3-4 lines, AI + Full-Stack highlights)
2. Education (keep, concise)
3. Work Experience (prioritize AI/Algorithm related experience)
4. Project Experience (emphasize: user-focused + scale + impact)
5. Skills List (AI related first)

===========================================

NEXT STEPS
===========================================

Would you like me to:
1. Output the complete optimized resume text
2. Generate PDF version
3. Modify a specific section in detail

===========================================

Generated by: Resume Interview Assistant
Date: 2026-05-05
`;

// Create PDF document
const doc = new PDFDocument({
  size: 'A4',
  margins: {
    top: 60,
    bottom: 60,
    left: 60,
    right: 60
  }
});

// Pipe output to file
const stream = fs.createWriteStream(outputFile);
doc.pipe(stream);

// Helper functions
function addTitle(text, y) {
  doc.fontSize(24)
     .font('Helvetica-Bold')
     .fillColor('#333333')
     .text(text, { align: 'center' });
}

function addSubtitle(text, y) {
  doc.fontSize(14)
     .font('Helvetica')
     .fillColor('#666666')
     .text(text, { align: 'center' });
}

function addSection(title) {
  doc.moveDown(0.5);
  doc.fontSize(14)
     .font('Helvetica-Bold')
     .fillColor('#2c3e50')
     .text(title, { underline: true });
  doc.moveDown(0.3);
}

function addContent(text) {
  doc.fontSize(11)
     .font('Helvetica')
     .fillColor('#333333')
     .text(text, { lineGap: 4 });
}

function addBullet(text) {
  doc.fontSize(11)
     .font('Helvetica')
     .fillColor('#333333')
     .text('  • ' + text, { lineGap: 2 });
}

function addSeparator() {
  doc.moveDown(0.3);
  doc.strokeColor('#cccccc')
     .lineWidth(0.5)
     .moveTo(60, doc.y)
     .lineTo(540, doc.y)
     .stroke();
  doc.moveDown(0.3);
}

// Build PDF
let y = 80;

// Title
doc.fontSize(24).font('Helvetica-Bold').fillColor('#2c3e50');
doc.text('Resume Optimization Guide', 60, y, { align: 'center', width: 480 });
y += 35;

doc.fontSize(14).font('Helvetica').fillColor('#666666');
doc.text('Software Engineer (AI) Position', 60, y, { align: 'center', width: 480 });
y += 25;

doc.fontSize(11).font('Helvetica').fillColor('#888888');
doc.text('Based on the resume analysis for: 姜植藂', 60, y, { align: 'center', width: 480 });
y += 40;

addSeparator();
addSection('CURRENT RESUME SUMMARY');

addContent('Personal Info:');
addBullet('Name: 姜植藂');
addBullet('Location: 北京通州');
addBullet('Email: jiangzhicong2516@163.com');
addBullet('Phone: 17600192516');

doc.moveDown(0.3);
addContent('Education:');
addBullet('中国政法大学 - 国际贸易学硕士 (2015-2018)');
addBullet('中国地质大学 - 数学与应用数学学士 (2009-2013)');

doc.moveDown(0.3);
addContent('Work Experience:');
addBullet('1. 北京外企德科人力资源有限公司 - 安全运营工程师/软件开发工程师 (2023.2-2025.4)');
addBullet('2. 北京盛创恒达房地产开发有限公司 - 算法工程师 (2018.7-2023.1)');

doc.moveDown(0.3);
addContent('Skills: Python、Java | 云计算安全、推荐算法、数据分析');

addSeparator();
addSection('JOB REQUIREMENTS ANALYSIS');

addContent('Software Engineer (AI) Core Requirements:');
addBullet('1. Design and deliver AI-driven Web/Mobile products');
addBullet('2. Full-stack development + AI/ML deep interest');
addBullet('3. Build scalable, user-focused applications');
addBullet('4. Cross-functional collaboration + end-to-end development');
addBullet('5. AI model integration optimization + mentoring');

addSeparator();
addSection('RESUME MODIFICATION SUGGESTIONS');

doc.fontSize(12).font('Helvetica-Bold').fillColor('#34495e');
doc.text('1. STRENGTHEN AI/ML RELATED EXPERIENCE');
doc.moveDown(0.2);

doc.fontSize(11).font('Helvetica').fillColor('#666666');
doc.text('Current:', { continued: false });
doc.font('Helvetica-Oblique').text('"召回率从 2% 提升至 5%，排序模型 AUC 达到 75%"', { indent: 20 });
doc.moveDown(0.2);
doc.font('Helvetica').text('Recommended:', { continued: false });
doc.font('Helvetica-Oblique').text('主导推荐系统算法优化，采用 Word2vec 进行物品 embedding 计算，结合用户行为序列进行兴趣建模，AUC 提升至 75%，召回率提升 150%（2%→5%）', { indent: 20 });
doc.moveDown(0.2);
doc.font('Helvetica').fillColor('#888888');
doc.text('Reason: Use technical terms to accurately describe AI algorithm work.', { indent: 20 });

doc.moveDown(0.5);
doc.fontSize(12).font('Helvetica-Bold').fillColor('#34495e');
doc.text('2. HIGHLIGHT FULL-STACK DEVELOPMENT SKILLS');
doc.moveDown(0.2);

doc.fontSize(11).font('Helvetica').fillColor('#666666');
doc.text('Current Project: 安全运营看板', { continued: false });
doc.moveDown(0.3);
doc.font('Helvetica').text('Recommended Additions:', { continued: false });
doc.moveDown(0.2);
addBullet('Frontend tech stack (if any)');
addBullet('Database design (SQL)');
addBullet('Log collection system architecture (ELK/Log Platform)');
doc.moveDown(0.2);
doc.font('Helvetica').text('Recommended Description:', { continued: false });
doc.moveDown(0.2);
doc.font('Helvetica-Oblique').fillColor('#333333');
doc.text('主导安全运营看板端到端开发，从架构设计到技术选型（Python + SQL + 可视化库），实现日志收集、存储、清洗、分析全链路，日处理数据量达百万级', { indent: 20 });

doc.moveDown(0.5);
doc.fontSize(12).font('Helvetica-Bold').fillColor('#34495e');
doc.text('3. ADD AI PRODUCT RELATED DESCRIPTIONS');
doc.moveDown(0.2);

doc.fontSize(11).font('Helvetica').fillColor('#666666');
doc.text('In project descriptions, include:', { continued: false });
doc.moveDown(0.2);
addBullet('AI model training/deployment involved');
addBullet('User experience optimization');
addBullet('Product iteration');
doc.moveDown(0.3);
doc.font('Helvetica').text('Recommended New Project Highlights:', { continued: false });
doc.moveDown(0.2);
doc.font('Helvetica-Oblique').fillColor('#333333');
doc.text('推荐系统日均服务用户请求 XX 次，算法响应时间 < 100ms，支撑业务 GMV 增长 XX%', { indent: 20 });

doc.moveDown(0.5);
doc.fontSize(12).font('Helvetica-Bold').fillColor('#34495e');
doc.text('4. STRENGTHEN CROSS-TEAM COLLABORATION');
doc.moveDown(0.2);

doc.fontSize(11).font('Helvetica').fillColor('#666666');
doc.text('Recommended additions to project management:', { continued: false });
doc.moveDown(0.2);
addBullet('Coordinate with security team, development team, product team');
addBullet('Close collaboration with data analysts');
addBullet('Guide junior engineers');

doc.moveDown(0.5);
doc.fontSize(12).font('Helvetica-Bold').fillColor('#34495e');
doc.text('5. SKILLS MODULE RESTRUCTURE');
doc.moveDown(0.3);

// Create a simple table
doc.fontSize(11).font('Helvetica').fillColor('#333333');
doc.text('Current:                              Recommended:', { indent: 0 });
doc.moveDown(0.2);
doc.text('编程语言：Python、Java           →    编程语言：Python、Java、SQL、Shell', { indent: 0 });
doc.moveDown(0.2);
doc.text('擅长领域：云计算安全...         →    擅长领域：', { indent: 0 });
doc.moveDown(0.15);
addBullet('AI/ML：推荐算法、NLP基础、模型优化');
addBullet('全栈开发：Web/Mobile 后端架构');
addBullet('数据工程：ETL、大数据分析、可视化');
addBullet('云安全：身份认证、权限管理');

// New page
doc.addPage();

// Title for second page
addSeparator();
addSection('RECOMMENDED RESUME STRUCTURE');

doc.fontSize(12).font('Helvetica-Bold').fillColor('#2c3e50');
doc.text('【Recommended Title】', { continued: false });
doc.font('Helvetica').fillColor('#333333');
doc.text(' Software Engineer | AI/ML | Full-Stack Developer', { continued: false });
doc.moveDown(0.5);

doc.fontSize(11).font('Helvetica').fillColor('#333333');
doc.text('1. Technical Summary (3-4 lines, AI + Full-Stack highlights)', { indent: 40 });
doc.moveDown(0.3);
doc.text('2. Education (keep, concise)', { indent: 40 });
doc.moveDown(0.3);
doc.text('3. Work Experience (prioritize AI/Algorithm related experience)', { indent: 40 });
doc.moveDown(0.3);
doc.text('4. Project Experience (emphasize: user-focused + scale + impact)', { indent: 40 });
doc.moveDown(0.3);
doc.text('5. Skills List (AI related first)', { indent: 40 });

addSeparator();
addSection('NEXT STEPS');

doc.fontSize(11).font('Helvetica').fillColor('#333333');
doc.text('Would you like me to:', { continued: false });
doc.moveDown(0.3);
addBullet('1. Output the complete optimized resume text');
addBullet('2. Generate PDF version');
addBullet('3. Modify a specific section in detail');

// Footer
doc.moveDown(2);
addSeparator();
doc.fontSize(10).font('Helvetica').fillColor('#888888');
doc.text('Generated by: Resume Interview Assistant', { align: 'center' });
doc.text('Date: 2026-05-05', { align: 'center' });

// Finalize PDF
doc.end();

stream.on('finish', () => {
  console.log(`PDF generated successfully: ${outputFile}`);
});

stream.on('error', (err) => {
  console.error('Error generating PDF:', err);
});